## File generated by the BNF Converter (bnfc 2.9.5).

CC = gcc -g
CCFLAGS = --ansi -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration ${CC_OPTS}

FLEX = flex
FLEX_OPTS = -Pbnf_

BISON = bison
BISON_OPTS = -t -pbnf_

OBJS = Absyn.o Buffer.o Lexer.o Parser.o Printer.o

.PHONY : clean distclean

all : Testbnf

clean :
	rm -f *.o Testbnf bnf.aux bnf.log bnf.pdf bnf.dvi bnf.ps bnf

distclean : clean
	rm -f Absyn.h Absyn.c Bison.h Buffer.h Buffer.c bnf.l Lexer.c bnf.y Parser.h Parser.c Printer.c Printer.h Skeleton.c Skeleton.h Test.c Makefile bnf.tex

Testbnf : ${OBJS} Test.o
	@echo "Linking Testbnf..."
	${CC} ${OBJS} Test.o -o Testbnf

Absyn.o : Absyn.c Absyn.h
	${CC} ${CCFLAGS} -c Absyn.c

Buffer.o : Buffer.c Buffer.h
	${CC} ${CCFLAGS} -c Buffer.c

Lexer.c : bnf.l
	${FLEX} ${FLEX_OPTS} -oLexer.c bnf.l

Parser.c Bison.h : bnf.y
	${BISON} ${BISON_OPTS} bnf.y -o Parser.c

Lexer.o : CCFLAGS+=-Wno-sign-conversion

Lexer.o : Lexer.c Bison.h
	${CC} ${CCFLAGS} -c Lexer.c

Parser.o : Parser.c Absyn.h Bison.h
	${CC} ${CCFLAGS} -c Parser.c

Printer.o : Printer.c Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Printer.c

Test.o : Test.c Parser.h Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Test.c
