/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

S  pS(FILE *inp);
S psS(const char *str);
Block  pBlock(FILE *inp);
Block psBlock(const char *str);
CMDS  pCMDS(FILE *inp);
CMDS psCMDS(const char *str);
CMD  pCMD(FILE *inp);
CMD psCMD(const char *str);
ATRIB  pATRIB(FILE *inp);
ATRIB psATRIB(const char *str);
EXP  pEXP(FILE *inp);
EXP psEXP(const char *str);
UAI  pUAI(FILE *inp);
UAI psUAI(const char *str);
OPerL  pOPerL(FILE *inp);
OPerL psOPerL(const char *str);
OPerA  pOPerA(FILE *inp);
OPerA psOPerA(const char *str);
OPL  pOPL(FILE *inp);
OPL psOPL(const char *str);
ZOIA  pZOIA(FILE *inp);
ZOIA psZOIA(const char *str);
VEMCA  pVEMCA(FILE *inp);
VEMCA psVEMCA(const char *str);
QUANTO  pQUANTO(FILE *inp);
QUANTO psQUANTO(const char *str);
PA  pPA(FILE *inp);
PA psPA(const char *str);
VALUE  pVALUE(FILE *inp);
VALUE psVALUE(const char *str);
Type  pType(FILE *inp);
Type psType(const char *str);
TREM  pTREM(FILE *inp);
TREM psTREM(const char *str);
STRUCT  pSTRUCT(FILE *inp);
STRUCT psSTRUCT(const char *str);
HeteroElements  pHeteroElements(FILE *inp);
HeteroElements psHeteroElements(const char *str);
HeteroElement  pHeteroElement(FILE *inp);
HeteroElement psHeteroElement(const char *str);
FUNC  pFUNC(FILE *inp);
FUNC psFUNC(const char *str);
VAILA  pVAILA(FILE *inp);
VAILA psVAILA(const char *str);
LABEL  pLABEL(FILE *inp);
LABEL psLABEL(const char *str);
ConjValues  pConjValues(FILE *inp);
ConjValues psConjValues(const char *str);
ConjValues2D  pConjValues2D(FILE *inp);
ConjValues2D psConjValues2D(const char *str);
PERMA  pPERMA(FILE *inp);
PERMA psPERMA(const char *str);
APONTA  pAPONTA(FILE *inp);
APONTA psAPONTA(const char *str);

#endif
