/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <ctype.h>   /* isspace */
#include <stddef.h>  /* size_t */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "Printer.h"

#define INDENT_WIDTH 2

int _n_;
char *buf_;
size_t cur_;
size_t buf_size;

/* You may wish to change the renderC functions */
void renderC(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppendC(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppendC('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppendC(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppendC(c);
     bufAppendC('\n');
     indent();
  }
  else if (c == ' ') bufAppendC(c);
  else if (c == 0) return;
  else
  {
     bufAppendC(c);
     bufAppendC(' ');
  }
}

int allIsSpace(String s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return 0;
  return 1;
}

void renderS(String s)
{
  if (*s) /* s[0] != '\0', string s not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppendS(s);
    } else {
      bufAppendS(s);
      bufAppendC(' ');
    }
  }
}

void indent(void)
{
  int n = _n_;
  while (--n >= 0)
    bufAppendC(' ');
}

void backup(void)
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppendC('\n');
  indent();
}
char *printS(S p)
{
  _n_ = 0;
  bufReset();
  ppS(p, 0);
  return buf_;
}
char *printBlock(Block p)
{
  _n_ = 0;
  bufReset();
  ppBlock(p, 0);
  return buf_;
}
char *printCMDS(CMDS p)
{
  _n_ = 0;
  bufReset();
  ppCMDS(p, 0);
  return buf_;
}
char *printCMD(CMD p)
{
  _n_ = 0;
  bufReset();
  ppCMD(p, 0);
  return buf_;
}
char *printATRIB(ATRIB p)
{
  _n_ = 0;
  bufReset();
  ppATRIB(p, 0);
  return buf_;
}
char *printEXP(EXP p)
{
  _n_ = 0;
  bufReset();
  ppEXP(p, 0);
  return buf_;
}
char *printUAI(UAI p)
{
  _n_ = 0;
  bufReset();
  ppUAI(p, 0);
  return buf_;
}
char *printOPerL(OPerL p)
{
  _n_ = 0;
  bufReset();
  ppOPerL(p, 0);
  return buf_;
}
char *printOPerA(OPerA p)
{
  _n_ = 0;
  bufReset();
  ppOPerA(p, 0);
  return buf_;
}
char *printOPL(OPL p)
{
  _n_ = 0;
  bufReset();
  ppOPL(p, 0);
  return buf_;
}
char *printZOIA(ZOIA p)
{
  _n_ = 0;
  bufReset();
  ppZOIA(p, 0);
  return buf_;
}
char *printVEMCA(VEMCA p)
{
  _n_ = 0;
  bufReset();
  ppVEMCA(p, 0);
  return buf_;
}
char *printQUANTO(QUANTO p)
{
  _n_ = 0;
  bufReset();
  ppQUANTO(p, 0);
  return buf_;
}
char *printPA(PA p)
{
  _n_ = 0;
  bufReset();
  ppPA(p, 0);
  return buf_;
}
char *printVALUE(VALUE p)
{
  _n_ = 0;
  bufReset();
  ppVALUE(p, 0);
  return buf_;
}
char *printType(Type p)
{
  _n_ = 0;
  bufReset();
  ppType(p, 0);
  return buf_;
}
char *printTREM(TREM p)
{
  _n_ = 0;
  bufReset();
  ppTREM(p, 0);
  return buf_;
}
char *printSTRUCT(STRUCT p)
{
  _n_ = 0;
  bufReset();
  ppSTRUCT(p, 0);
  return buf_;
}
char *printHeteroElements(HeteroElements p)
{
  _n_ = 0;
  bufReset();
  ppHeteroElements(p, 0);
  return buf_;
}
char *printHeteroElement(HeteroElement p)
{
  _n_ = 0;
  bufReset();
  ppHeteroElement(p, 0);
  return buf_;
}
char *printFUNC(FUNC p)
{
  _n_ = 0;
  bufReset();
  ppFUNC(p, 0);
  return buf_;
}
char *printVAILA(VAILA p)
{
  _n_ = 0;
  bufReset();
  ppVAILA(p, 0);
  return buf_;
}
char *printLABEL(LABEL p)
{
  _n_ = 0;
  bufReset();
  ppLABEL(p, 0);
  return buf_;
}
char *printConjValues(ConjValues p)
{
  _n_ = 0;
  bufReset();
  ppConjValues(p, 0);
  return buf_;
}
char *printConjValues2D(ConjValues2D p)
{
  _n_ = 0;
  bufReset();
  ppConjValues2D(p, 0);
  return buf_;
}
char *printPERMA(PERMA p)
{
  _n_ = 0;
  bufReset();
  ppPERMA(p, 0);
  return buf_;
}
char *printAPONTA(APONTA p)
{
  _n_ = 0;
  bufReset();
  ppAPONTA(p, 0);
  return buf_;
}
char *showS(S p)
{
  _n_ = 0;
  bufReset();
  shS(p);
  return buf_;
}
char *showBlock(Block p)
{
  _n_ = 0;
  bufReset();
  shBlock(p);
  return buf_;
}
char *showCMDS(CMDS p)
{
  _n_ = 0;
  bufReset();
  shCMDS(p);
  return buf_;
}
char *showCMD(CMD p)
{
  _n_ = 0;
  bufReset();
  shCMD(p);
  return buf_;
}
char *showATRIB(ATRIB p)
{
  _n_ = 0;
  bufReset();
  shATRIB(p);
  return buf_;
}
char *showEXP(EXP p)
{
  _n_ = 0;
  bufReset();
  shEXP(p);
  return buf_;
}
char *showUAI(UAI p)
{
  _n_ = 0;
  bufReset();
  shUAI(p);
  return buf_;
}
char *showOPerL(OPerL p)
{
  _n_ = 0;
  bufReset();
  shOPerL(p);
  return buf_;
}
char *showOPerA(OPerA p)
{
  _n_ = 0;
  bufReset();
  shOPerA(p);
  return buf_;
}
char *showOPL(OPL p)
{
  _n_ = 0;
  bufReset();
  shOPL(p);
  return buf_;
}
char *showZOIA(ZOIA p)
{
  _n_ = 0;
  bufReset();
  shZOIA(p);
  return buf_;
}
char *showVEMCA(VEMCA p)
{
  _n_ = 0;
  bufReset();
  shVEMCA(p);
  return buf_;
}
char *showQUANTO(QUANTO p)
{
  _n_ = 0;
  bufReset();
  shQUANTO(p);
  return buf_;
}
char *showPA(PA p)
{
  _n_ = 0;
  bufReset();
  shPA(p);
  return buf_;
}
char *showVALUE(VALUE p)
{
  _n_ = 0;
  bufReset();
  shVALUE(p);
  return buf_;
}
char *showType(Type p)
{
  _n_ = 0;
  bufReset();
  shType(p);
  return buf_;
}
char *showTREM(TREM p)
{
  _n_ = 0;
  bufReset();
  shTREM(p);
  return buf_;
}
char *showSTRUCT(STRUCT p)
{
  _n_ = 0;
  bufReset();
  shSTRUCT(p);
  return buf_;
}
char *showHeteroElements(HeteroElements p)
{
  _n_ = 0;
  bufReset();
  shHeteroElements(p);
  return buf_;
}
char *showHeteroElement(HeteroElement p)
{
  _n_ = 0;
  bufReset();
  shHeteroElement(p);
  return buf_;
}
char *showFUNC(FUNC p)
{
  _n_ = 0;
  bufReset();
  shFUNC(p);
  return buf_;
}
char *showVAILA(VAILA p)
{
  _n_ = 0;
  bufReset();
  shVAILA(p);
  return buf_;
}
char *showLABEL(LABEL p)
{
  _n_ = 0;
  bufReset();
  shLABEL(p);
  return buf_;
}
char *showConjValues(ConjValues p)
{
  _n_ = 0;
  bufReset();
  shConjValues(p);
  return buf_;
}
char *showConjValues2D(ConjValues2D p)
{
  _n_ = 0;
  bufReset();
  shConjValues2D(p);
  return buf_;
}
char *showPERMA(PERMA p)
{
  _n_ = 0;
  bufReset();
  shPERMA(p);
  return buf_;
}
char *showAPONTA(APONTA p)
{
  _n_ = 0;
  bufReset();
  shAPONTA(p);
  return buf_;
}
void ppS(S p, int _i_)
{
  switch(p->kind)
  {
  case is_Sst:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("main");
    renderS("deus");
    renderS("do");
    renderS("ceu");
    ppBlock(p->u.sst_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing S!\n");
    exit(1);
  }
}

void ppBlock(Block p, int _i_)
{
  switch(p->kind)
  {
  case is_LBlock:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('{');
    ppCMDS(p->u.lblock_.cmds_, 0);
    renderC('}');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Block!\n");
    exit(1);
  }
}

void ppCMDS(CMDS p, int _i_)
{
  switch(p->kind)
  {
  case is_CMDSCMD:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCMD(p->u.cmdscmd_.cmd_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDS1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppCMD(p->u.cmds1_.cmd_, 0);
    ppCMDS(p->u.cmds1_.cmds_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CMDS!\n");
    exit(1);
  }
}

void ppCMD(CMD p, int _i_)
{
  switch(p->kind)
  {
  case is_CMDATRIB:
    if (_i_ > 0) renderC(_L_PAREN);
    ppATRIB(p->u.cmdatrib_.atrib_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDEXP:
    if (_i_ > 0) renderC(_L_PAREN);
    ppEXP(p->u.cmdexp_.exp_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDUAI:
    if (_i_ > 0) renderC(_L_PAREN);
    ppUAI(p->u.cmduai_.uai_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDQUANTO:
    if (_i_ > 0) renderC(_L_PAREN);
    ppQUANTO(p->u.cmdquanto_.quanto_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDPA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPA(p->u.cmdpa_.pa_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDZOIA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppZOIA(p->u.cmdzoia_.zoia_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDVEMCA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVEMCA(p->u.cmdvemca_.vemca_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDPERMA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppPERMA(p->u.cmdperma_.perma_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDTREM:
    if (_i_ > 0) renderC(_L_PAREN);
    ppTREM(p->u.cmdtrem_.trem_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDFUNC:
    if (_i_ > 0) renderC(_L_PAREN);
    ppFUNC(p->u.cmdfunc_.func_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDVAILA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVAILA(p->u.cmdvaila_.vaila_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDLABEL:
    if (_i_ > 0) renderC(_L_PAREN);
    ppLABEL(p->u.cmdlabel_.label_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDSTRUCT:
    if (_i_ > 0) renderC(_L_PAREN);
    ppSTRUCT(p->u.cmdstruct_.struct_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_CMDAPONTA:
    if (_i_ > 0) renderC(_L_PAREN);
    ppAPONTA(p->u.cmdaponta_.aponta_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing CMD!\n");
    exit(1);
  }
}

void ppATRIB(ATRIB p, int _i_)
{
  switch(p->kind)
  {
  case is_ATRIB1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.atrib1_.type_, 0);
    ppIdent(p->u.atrib1_.ident_, 0);
    renderC('=');
    ppVALUE(p->u.atrib1_.value_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ATRIB2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.atrib2_.type_, 0);
    ppIdent(p->u.atrib2_.ident_, 0);
    renderC('=');
    ppEXP(p->u.atrib2_.exp_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ATRIB3:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atrib3_.ident_, 0);
    renderC('=');
    ppVALUE(p->u.atrib3_.value_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ATRIB4:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.atrib4_.ident_, 0);
    renderC('=');
    ppEXP(p->u.atrib4_.exp_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ATRIB!\n");
    exit(1);
  }
}

void ppEXP(EXP p, int _i_)
{
  switch(p->kind)
  {
  case is_EXP1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppEXP(p->u.exp1_.exp_1, 0);
    ppOPerA(p->u.exp1_.opera_, 0);
    ppEXP(p->u.exp1_.exp_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EXP2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppEXP(p->u.exp2_.exp_1, 0);
    ppOPerL(p->u.exp2_.operl_, 0);
    ppEXP(p->u.exp2_.exp_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EXP3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('(');
    ppEXP(p->u.exp3_.exp_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_EXPVALUE:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVALUE(p->u.expvalue_.value_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing EXP!\n");
    exit(1);
  }
}

void ppUAI(UAI p, int _i_)
{
  switch(p->kind)
  {
  case is_UAI1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Uai");
    renderC('(');
    ppOPL(p->u.uai1_.opl_, 0);
    renderC(')');
    ppBlock(p->u.uai1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_UAI2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Uai");
    renderC('(');
    ppOPL(p->u.uai2_.opl_, 0);
    renderC(')');
    ppBlock(p->u.uai2_.block_1, 0);
    renderS("So");
    ppBlock(p->u.uai2_.block_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing UAI!\n");
    exit(1);
  }
}

void ppOPerL(OPerL p, int _i_)
{
  switch(p->kind)
  {
  case is_OPerL1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('>');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS(">=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('<');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL4:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL5:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("==");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL6:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("<>");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL7:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("!=");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerL8:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("&&");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OPerL!\n");
    exit(1);
  }
}

void ppOPerA(OPerA p, int _i_)
{
  switch(p->kind)
  {
  case is_OPerA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('/');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerA2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('*');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerA3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('+');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_OPerA4:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('-');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OPerA!\n");
    exit(1);
  }
}

void ppOPL(OPL p, int _i_)
{
  switch(p->kind)
  {
  case is_OPL1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppEXP(p->u.opl1_.exp_1, 0);
    ppOPerL(p->u.opl1_.operl_, 0);
    ppEXP(p->u.opl1_.exp_2, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing OPL!\n");
    exit(1);
  }
}

void ppZOIA(ZOIA p, int _i_)
{
  switch(p->kind)
  {
  case is_ZOIA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Zoia");
    renderC('(');
    ppVALUE(p->u.zoia1_.value_, 0);
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ZOIA2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Zoia");
    renderC('(');
    ppVALUE(p->u.zoia2_.value_1, 0);
    renderC(',');
    ppVALUE(p->u.zoia2_.value_2, 0);
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ZOIA3:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Zoia");
    renderC('(');
    ppVALUE(p->u.zoia3_.value_1, 0);
    renderC(',');
    ppVALUE(p->u.zoia3_.value_2, 0);
    renderC(',');
    ppVALUE(p->u.zoia3_.value_3, 0);
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ZOIA!\n");
    exit(1);
  }
}

void ppVEMCA(VEMCA p, int _i_)
{
  switch(p->kind)
  {
  case is_VEMCA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Vemca");
    renderC('(');
    ppType(p->u.vemca1_.type_, 0);
    ppIdent(p->u.vemca1_.ident_, 0);
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VEMCA!\n");
    exit(1);
  }
}

void ppQUANTO(QUANTO p, int _i_)
{
  switch(p->kind)
  {
  case is_QUANTO1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Quanto");
    renderC('(');
    ppOPL(p->u.quanto1_.opl_, 0);
    renderC(')');
    ppBlock(p->u.quanto1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing QUANTO!\n");
    exit(1);
  }
}

void ppPA(PA p, int _i_)
{
  switch(p->kind)
  {
  case is_PA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Pa");
    renderC('(');
    ppType(p->u.pa1_.type_, 0);
    ppIdent(p->u.pa1_.ident_1, 0);
    renderC('=');
    ppVALUE(p->u.pa1_.value_, 0);
    renderC('|');
    ppOPL(p->u.pa1_.opl_, 0);
    renderC('|');
    ppIdent(p->u.pa1_.ident_2, 0);
    renderC('=');
    ppEXP(p->u.pa1_.exp_, 0);
    renderC(')');
    ppBlock(p->u.pa1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing PA!\n");
    exit(1);
  }
}

void ppVALUE(VALUE p, int _i_)
{
  switch(p->kind)
  {
  case is_VALUEIdent:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.valueident_.ident_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUE1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.value1_.ident_, 0);
    renderC('[');
    ppEXP(p->u.value1_.exp_, 0);
    renderC(']');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUE2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.value2_.ident_, 0);
    renderC('[');
    ppEXP(p->u.value2_.exp_1, 0);
    renderC(']');
    renderC('[');
    ppEXP(p->u.value2_.exp_2, 0);
    renderC(']');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUEString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.valuestring_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUEInteger:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.valueinteger_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_VALUEDouble:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.valuedouble_.double_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VALUE!\n");
    exit(1);
  }
}

void ppType(Type p, int _i_)
{
  switch(p->kind)
  {
  case is_Type_intero:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("intero");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_floati:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("floati");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_Type_stringo:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("stringo");
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Type!\n");
    exit(1);
  }
}

void ppTREM(TREM p, int _i_)
{
  switch(p->kind)
  {
  case is_TREM1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.trem1_.type_, 0);
    ppIdent(p->u.trem1_.ident_, 0);
    renderC('[');
    ppInteger(p->u.trem1_.integer_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TREM2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.trem2_.type_, 0);
    ppIdent(p->u.trem2_.ident_, 0);
    renderC('[');
    ppInteger(p->u.trem2_.integer_, 0);
    renderC(']');
    renderC('=');
    renderC('[');
    ppConjValues(p->u.trem2_.conjvalues_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TREM3:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.trem3_.type_, 0);
    ppIdent(p->u.trem3_.ident_, 0);
    renderC('[');
    ppInteger(p->u.trem3_.integer_1, 0);
    renderC(']');
    renderC('[');
    ppInteger(p->u.trem3_.integer_2, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_TREM4:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.trem4_.type_, 0);
    ppIdent(p->u.trem4_.ident_, 0);
    renderC('[');
    ppInteger(p->u.trem4_.integer_1, 0);
    renderC(']');
    renderC('[');
    ppInteger(p->u.trem4_.integer_2, 0);
    renderC(']');
    renderC('=');
    renderC('[');
    ppConjValues2D(p->u.trem4_.conjvalues2d_, 0);
    renderC(']');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing TREM!\n");
    exit(1);
  }
}

void ppSTRUCT(STRUCT p, int _i_)
{
  switch(p->kind)
  {
  case is_STRUCT1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Istrut");
    renderC('[');
    ppInteger(p->u.struct1_.integer_, 0);
    renderC(']');
    renderC('=');
    renderC('{');
    ppHeteroElements(p->u.struct1_.heteroelements_, 0);
    renderC('}');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing STRUCT!\n");
    exit(1);
  }
}

void ppHeteroElements(HeteroElements p, int _i_)
{
  switch(p->kind)
  {
  case is_HeteroElementsHeteroElement:
    if (_i_ > 0) renderC(_L_PAREN);
    ppHeteroElement(p->u.heteroelementsheteroelement_.heteroelement_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_HeteroElements1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppHeteroElement(p->u.heteroelements1_.heteroelement_, 0);
    renderC(',');
    ppHeteroElements(p->u.heteroelements1_.heteroelements_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing HeteroElements!\n");
    exit(1);
  }
}

void ppHeteroElement(HeteroElement p, int _i_)
{
  switch(p->kind)
  {
  case is_HeteroElementString:
    if (_i_ > 0) renderC(_L_PAREN);
    ppString(p->u.heteroelementstring_.string_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_HeteroElementDouble:
    if (_i_ > 0) renderC(_L_PAREN);
    ppDouble(p->u.heteroelementdouble_.double_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_HeteroElementInteger:
    if (_i_ > 0) renderC(_L_PAREN);
    ppInteger(p->u.heteroelementinteger_.integer_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing HeteroElement!\n");
    exit(1);
  }
}

void ppFUNC(FUNC p, int _i_)
{
  switch(p->kind)
  {
  case is_FUNC1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Funciona_Assim");
    ppIdent(p->u.func1_.ident_, 0);
    renderC('(');
    renderC(')');
    ppBlock(p->u.func1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FUNC2:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.func2_.ident_, 0);
    renderC('(');
    renderC(')');
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_FUNC3:
    if (_i_ > 0) renderC(_L_PAREN);
    ppIdent(p->u.func3_.ident_, 0);
    renderC('(');
    ppVALUE(p->u.func3_.value_, 0);
    renderC(')');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing FUNC!\n");
    exit(1);
  }
}

void ppVAILA(VAILA p, int _i_)
{
  switch(p->kind)
  {
  case is_VAILA1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Vaila");
    ppInteger(p->u.vaila1_.integer_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing VAILA!\n");
    exit(1);
  }
}

void ppLABEL(LABEL p, int _i_)
{
  switch(p->kind)
  {
  case is_LABEL1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("LABEL");
    ppInteger(p->u.label1_.integer_, 0);
    renderC(':');
    ppBlock(p->u.label1_.block_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing LABEL!\n");
    exit(1);
  }
}

void ppConjValues(ConjValues p, int _i_)
{
  switch(p->kind)
  {
  case is_ConjValuesVALUE:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVALUE(p->u.conjvaluesvalue_.value_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConjValues1:
    if (_i_ > 0) renderC(_L_PAREN);
    ppVALUE(p->u.conjvalues1_.value_, 0);
    renderC(',');
    ppConjValues(p->u.conjvalues1_.conjvalues_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConjValues!\n");
    exit(1);
  }
}

void ppConjValues2D(ConjValues2D p, int _i_)
{
  switch(p->kind)
  {
  case is_ConjValues2D1:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('[');
    ppConjValues(p->u.conjvalues2d1_.conjvalues_, 0);
    renderC(']');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  case is_ConjValues2D2:
    if (_i_ > 0) renderC(_L_PAREN);
    renderC('[');
    ppConjValues(p->u.conjvalues2d2_.conjvalues_, 0);
    renderC(']');
    renderC(',');
    ppConjValues2D(p->u.conjvalues2d2_.conjvalues2d_, 0);
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ConjValues2D!\n");
    exit(1);
  }
}

void ppPERMA(PERMA p, int _i_)
{
  switch(p->kind)
  {
  case is_LConst:
    if (_i_ > 0) renderC(_L_PAREN);
    renderS("Perma");
    ppType(p->u.lconst_.type_, 0);
    ppIdent(p->u.lconst_.ident_, 0);
    renderC('=');
    ppVALUE(p->u.lconst_.value_, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing PERMA!\n");
    exit(1);
  }
}

void ppAPONTA(APONTA p, int _i_)
{
  switch(p->kind)
  {
  case is_LPoint:
    if (_i_ > 0) renderC(_L_PAREN);
    ppType(p->u.lpoint_.type_, 0);
    renderC('*');
    ppIdent(p->u.lpoint_.ident_1, 0);
    renderC('=');
    ppIdent(p->u.lpoint_.ident_2, 0);
    renderC(';');
    if (_i_ > 0) renderC(_R_PAREN);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing APONTA!\n");
    exit(1);
  }
}

void ppInteger(Integer n, int i)
{
  char tmp[20];
  sprintf(tmp, "%d", n);
  renderS(tmp);
}
void ppDouble(Double d, int i)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  renderS(tmp);
}
void ppChar(Char c, int i)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
  bufAppendC(' ');
}
void ppString(String s, int i)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
  bufAppendC(' ');
}
void ppIdent(String s, int i)
{
  renderS(s);
}

void shS(S p)
{
  switch(p->kind)
  {
  case is_Sst:
    bufAppendC('(');

    bufAppendS("Sst");

    bufAppendC(' ');

    shBlock(p->u.sst_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing S!\n");
    exit(1);
  }
}

void shBlock(Block p)
{
  switch(p->kind)
  {
  case is_LBlock:
    bufAppendC('(');

    bufAppendS("LBlock");

    bufAppendC(' ');

    shCMDS(p->u.lblock_.cmds_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Block!\n");
    exit(1);
  }
}

void shCMDS(CMDS p)
{
  switch(p->kind)
  {
  case is_CMDSCMD:
    bufAppendC('(');

    bufAppendS("CMDSCMD");

    bufAppendC(' ');

    shCMD(p->u.cmdscmd_.cmd_);

    bufAppendC(')');

    break;
  case is_CMDS1:
    bufAppendC('(');

    bufAppendS("CMDS1");

    bufAppendC(' ');

    shCMD(p->u.cmds1_.cmd_);
  bufAppendC(' ');
    shCMDS(p->u.cmds1_.cmds_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CMDS!\n");
    exit(1);
  }
}

void shCMD(CMD p)
{
  switch(p->kind)
  {
  case is_CMDATRIB:
    bufAppendC('(');

    bufAppendS("CMDATRIB");

    bufAppendC(' ');

    shATRIB(p->u.cmdatrib_.atrib_);

    bufAppendC(')');

    break;
  case is_CMDEXP:
    bufAppendC('(');

    bufAppendS("CMDEXP");

    bufAppendC(' ');

    shEXP(p->u.cmdexp_.exp_);

    bufAppendC(')');

    break;
  case is_CMDUAI:
    bufAppendC('(');

    bufAppendS("CMDUAI");

    bufAppendC(' ');

    shUAI(p->u.cmduai_.uai_);

    bufAppendC(')');

    break;
  case is_CMDQUANTO:
    bufAppendC('(');

    bufAppendS("CMDQUANTO");

    bufAppendC(' ');

    shQUANTO(p->u.cmdquanto_.quanto_);

    bufAppendC(')');

    break;
  case is_CMDPA:
    bufAppendC('(');

    bufAppendS("CMDPA");

    bufAppendC(' ');

    shPA(p->u.cmdpa_.pa_);

    bufAppendC(')');

    break;
  case is_CMDZOIA:
    bufAppendC('(');

    bufAppendS("CMDZOIA");

    bufAppendC(' ');

    shZOIA(p->u.cmdzoia_.zoia_);

    bufAppendC(')');

    break;
  case is_CMDVEMCA:
    bufAppendC('(');

    bufAppendS("CMDVEMCA");

    bufAppendC(' ');

    shVEMCA(p->u.cmdvemca_.vemca_);

    bufAppendC(')');

    break;
  case is_CMDPERMA:
    bufAppendC('(');

    bufAppendS("CMDPERMA");

    bufAppendC(' ');

    shPERMA(p->u.cmdperma_.perma_);

    bufAppendC(')');

    break;
  case is_CMDTREM:
    bufAppendC('(');

    bufAppendS("CMDTREM");

    bufAppendC(' ');

    shTREM(p->u.cmdtrem_.trem_);

    bufAppendC(')');

    break;
  case is_CMDFUNC:
    bufAppendC('(');

    bufAppendS("CMDFUNC");

    bufAppendC(' ');

    shFUNC(p->u.cmdfunc_.func_);

    bufAppendC(')');

    break;
  case is_CMDVAILA:
    bufAppendC('(');

    bufAppendS("CMDVAILA");

    bufAppendC(' ');

    shVAILA(p->u.cmdvaila_.vaila_);

    bufAppendC(')');

    break;
  case is_CMDLABEL:
    bufAppendC('(');

    bufAppendS("CMDLABEL");

    bufAppendC(' ');

    shLABEL(p->u.cmdlabel_.label_);

    bufAppendC(')');

    break;
  case is_CMDSTRUCT:
    bufAppendC('(');

    bufAppendS("CMDSTRUCT");

    bufAppendC(' ');

    shSTRUCT(p->u.cmdstruct_.struct_);

    bufAppendC(')');

    break;
  case is_CMDAPONTA:
    bufAppendC('(');

    bufAppendS("CMDAPONTA");

    bufAppendC(' ');

    shAPONTA(p->u.cmdaponta_.aponta_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing CMD!\n");
    exit(1);
  }
}

void shATRIB(ATRIB p)
{
  switch(p->kind)
  {
  case is_ATRIB1:
    bufAppendC('(');

    bufAppendS("ATRIB1");

    bufAppendC(' ');

    shType(p->u.atrib1_.type_);
  bufAppendC(' ');
    shIdent(p->u.atrib1_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.atrib1_.value_);

    bufAppendC(')');

    break;
  case is_ATRIB2:
    bufAppendC('(');

    bufAppendS("ATRIB2");

    bufAppendC(' ');

    shType(p->u.atrib2_.type_);
  bufAppendC(' ');
    shIdent(p->u.atrib2_.ident_);
  bufAppendC(' ');
    shEXP(p->u.atrib2_.exp_);

    bufAppendC(')');

    break;
  case is_ATRIB3:
    bufAppendC('(');

    bufAppendS("ATRIB3");

    bufAppendC(' ');

    shIdent(p->u.atrib3_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.atrib3_.value_);

    bufAppendC(')');

    break;
  case is_ATRIB4:
    bufAppendC('(');

    bufAppendS("ATRIB4");

    bufAppendC(' ');

    shIdent(p->u.atrib4_.ident_);
  bufAppendC(' ');
    shEXP(p->u.atrib4_.exp_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ATRIB!\n");
    exit(1);
  }
}

void shEXP(EXP p)
{
  switch(p->kind)
  {
  case is_EXP1:
    bufAppendC('(');

    bufAppendS("EXP1");

    bufAppendC(' ');

    shEXP(p->u.exp1_.exp_1);
  bufAppendC(' ');
    shOPerA(p->u.exp1_.opera_);
  bufAppendC(' ');
    shEXP(p->u.exp1_.exp_2);

    bufAppendC(')');

    break;
  case is_EXP2:
    bufAppendC('(');

    bufAppendS("EXP2");

    bufAppendC(' ');

    shEXP(p->u.exp2_.exp_1);
  bufAppendC(' ');
    shOPerL(p->u.exp2_.operl_);
  bufAppendC(' ');
    shEXP(p->u.exp2_.exp_2);

    bufAppendC(')');

    break;
  case is_EXP3:
    bufAppendC('(');

    bufAppendS("EXP3");

    bufAppendC(' ');

    shEXP(p->u.exp3_.exp_);

    bufAppendC(')');

    break;
  case is_EXPVALUE:
    bufAppendC('(');

    bufAppendS("EXPVALUE");

    bufAppendC(' ');

    shVALUE(p->u.expvalue_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing EXP!\n");
    exit(1);
  }
}

void shUAI(UAI p)
{
  switch(p->kind)
  {
  case is_UAI1:
    bufAppendC('(');

    bufAppendS("UAI1");

    bufAppendC(' ');

    shOPL(p->u.uai1_.opl_);
  bufAppendC(' ');
    shBlock(p->u.uai1_.block_);

    bufAppendC(')');

    break;
  case is_UAI2:
    bufAppendC('(');

    bufAppendS("UAI2");

    bufAppendC(' ');

    shOPL(p->u.uai2_.opl_);
  bufAppendC(' ');
    shBlock(p->u.uai2_.block_1);
  bufAppendC(' ');
    shBlock(p->u.uai2_.block_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing UAI!\n");
    exit(1);
  }
}

void shOPerL(OPerL p)
{
  switch(p->kind)
  {
  case is_OPerL1:

    bufAppendS("OPerL1");




    break;
  case is_OPerL2:

    bufAppendS("OPerL2");




    break;
  case is_OPerL3:

    bufAppendS("OPerL3");




    break;
  case is_OPerL4:

    bufAppendS("OPerL4");




    break;
  case is_OPerL5:

    bufAppendS("OPerL5");




    break;
  case is_OPerL6:

    bufAppendS("OPerL6");




    break;
  case is_OPerL7:

    bufAppendS("OPerL7");




    break;
  case is_OPerL8:

    bufAppendS("OPerL8");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OPerL!\n");
    exit(1);
  }
}

void shOPerA(OPerA p)
{
  switch(p->kind)
  {
  case is_OPerA1:

    bufAppendS("OPerA1");




    break;
  case is_OPerA2:

    bufAppendS("OPerA2");




    break;
  case is_OPerA3:

    bufAppendS("OPerA3");




    break;
  case is_OPerA4:

    bufAppendS("OPerA4");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OPerA!\n");
    exit(1);
  }
}

void shOPL(OPL p)
{
  switch(p->kind)
  {
  case is_OPL1:
    bufAppendC('(');

    bufAppendS("OPL1");

    bufAppendC(' ');

    shEXP(p->u.opl1_.exp_1);
  bufAppendC(' ');
    shOPerL(p->u.opl1_.operl_);
  bufAppendC(' ');
    shEXP(p->u.opl1_.exp_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing OPL!\n");
    exit(1);
  }
}

void shZOIA(ZOIA p)
{
  switch(p->kind)
  {
  case is_ZOIA1:
    bufAppendC('(');

    bufAppendS("ZOIA1");

    bufAppendC(' ');

    shVALUE(p->u.zoia1_.value_);

    bufAppendC(')');

    break;
  case is_ZOIA2:
    bufAppendC('(');

    bufAppendS("ZOIA2");

    bufAppendC(' ');

    shVALUE(p->u.zoia2_.value_1);
  bufAppendC(' ');
    shVALUE(p->u.zoia2_.value_2);

    bufAppendC(')');

    break;
  case is_ZOIA3:
    bufAppendC('(');

    bufAppendS("ZOIA3");

    bufAppendC(' ');

    shVALUE(p->u.zoia3_.value_1);
  bufAppendC(' ');
    shVALUE(p->u.zoia3_.value_2);
  bufAppendC(' ');
    shVALUE(p->u.zoia3_.value_3);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ZOIA!\n");
    exit(1);
  }
}

void shVEMCA(VEMCA p)
{
  switch(p->kind)
  {
  case is_VEMCA1:
    bufAppendC('(');

    bufAppendS("VEMCA1");

    bufAppendC(' ');

    shType(p->u.vemca1_.type_);
  bufAppendC(' ');
    shIdent(p->u.vemca1_.ident_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing VEMCA!\n");
    exit(1);
  }
}

void shQUANTO(QUANTO p)
{
  switch(p->kind)
  {
  case is_QUANTO1:
    bufAppendC('(');

    bufAppendS("QUANTO1");

    bufAppendC(' ');

    shOPL(p->u.quanto1_.opl_);
  bufAppendC(' ');
    shBlock(p->u.quanto1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing QUANTO!\n");
    exit(1);
  }
}

void shPA(PA p)
{
  switch(p->kind)
  {
  case is_PA1:
    bufAppendC('(');

    bufAppendS("PA1");

    bufAppendC(' ');

    shType(p->u.pa1_.type_);
  bufAppendC(' ');
    shIdent(p->u.pa1_.ident_1);
  bufAppendC(' ');
    shVALUE(p->u.pa1_.value_);
  bufAppendC(' ');
    shOPL(p->u.pa1_.opl_);
  bufAppendC(' ');
    shIdent(p->u.pa1_.ident_2);
  bufAppendC(' ');
    shEXP(p->u.pa1_.exp_);
  bufAppendC(' ');
    shBlock(p->u.pa1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing PA!\n");
    exit(1);
  }
}

void shVALUE(VALUE p)
{
  switch(p->kind)
  {
  case is_VALUEIdent:
    bufAppendC('(');

    bufAppendS("VALUEIdent");

    bufAppendC(' ');

    shIdent(p->u.valueident_.ident_);

    bufAppendC(')');

    break;
  case is_VALUE1:
    bufAppendC('(');

    bufAppendS("VALUE1");

    bufAppendC(' ');

    shIdent(p->u.value1_.ident_);
  bufAppendC(' ');
    shEXP(p->u.value1_.exp_);

    bufAppendC(')');

    break;
  case is_VALUE2:
    bufAppendC('(');

    bufAppendS("VALUE2");

    bufAppendC(' ');

    shIdent(p->u.value2_.ident_);
  bufAppendC(' ');
    shEXP(p->u.value2_.exp_1);
  bufAppendC(' ');
    shEXP(p->u.value2_.exp_2);

    bufAppendC(')');

    break;
  case is_VALUEString:
    bufAppendC('(');

    bufAppendS("VALUEString");

    bufAppendC(' ');

    shString(p->u.valuestring_.string_);

    bufAppendC(')');

    break;
  case is_VALUEInteger:
    bufAppendC('(');

    bufAppendS("VALUEInteger");

    bufAppendC(' ');

    shInteger(p->u.valueinteger_.integer_);

    bufAppendC(')');

    break;
  case is_VALUEDouble:
    bufAppendC('(');

    bufAppendS("VALUEDouble");

    bufAppendC(' ');

    shDouble(p->u.valuedouble_.double_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing VALUE!\n");
    exit(1);
  }
}

void shType(Type p)
{
  switch(p->kind)
  {
  case is_Type_intero:

    bufAppendS("Type_intero");




    break;
  case is_Type_floati:

    bufAppendS("Type_floati");




    break;
  case is_Type_stringo:

    bufAppendS("Type_stringo");




    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing Type!\n");
    exit(1);
  }
}

void shTREM(TREM p)
{
  switch(p->kind)
  {
  case is_TREM1:
    bufAppendC('(');

    bufAppendS("TREM1");

    bufAppendC(' ');

    shType(p->u.trem1_.type_);
  bufAppendC(' ');
    shIdent(p->u.trem1_.ident_);
  bufAppendC(' ');
    shInteger(p->u.trem1_.integer_);

    bufAppendC(')');

    break;
  case is_TREM2:
    bufAppendC('(');

    bufAppendS("TREM2");

    bufAppendC(' ');

    shType(p->u.trem2_.type_);
  bufAppendC(' ');
    shIdent(p->u.trem2_.ident_);
  bufAppendC(' ');
    shInteger(p->u.trem2_.integer_);
  bufAppendC(' ');
    shConjValues(p->u.trem2_.conjvalues_);

    bufAppendC(')');

    break;
  case is_TREM3:
    bufAppendC('(');

    bufAppendS("TREM3");

    bufAppendC(' ');

    shType(p->u.trem3_.type_);
  bufAppendC(' ');
    shIdent(p->u.trem3_.ident_);
  bufAppendC(' ');
    shInteger(p->u.trem3_.integer_1);
  bufAppendC(' ');
    shInteger(p->u.trem3_.integer_2);

    bufAppendC(')');

    break;
  case is_TREM4:
    bufAppendC('(');

    bufAppendS("TREM4");

    bufAppendC(' ');

    shType(p->u.trem4_.type_);
  bufAppendC(' ');
    shIdent(p->u.trem4_.ident_);
  bufAppendC(' ');
    shInteger(p->u.trem4_.integer_1);
  bufAppendC(' ');
    shInteger(p->u.trem4_.integer_2);
  bufAppendC(' ');
    shConjValues2D(p->u.trem4_.conjvalues2d_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing TREM!\n");
    exit(1);
  }
}

void shSTRUCT(STRUCT p)
{
  switch(p->kind)
  {
  case is_STRUCT1:
    bufAppendC('(');

    bufAppendS("STRUCT1");

    bufAppendC(' ');

    shInteger(p->u.struct1_.integer_);
  bufAppendC(' ');
    shHeteroElements(p->u.struct1_.heteroelements_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing STRUCT!\n");
    exit(1);
  }
}

void shHeteroElements(HeteroElements p)
{
  switch(p->kind)
  {
  case is_HeteroElementsHeteroElement:
    bufAppendC('(');

    bufAppendS("HeteroElementsHeteroElement");

    bufAppendC(' ');

    shHeteroElement(p->u.heteroelementsheteroelement_.heteroelement_);

    bufAppendC(')');

    break;
  case is_HeteroElements1:
    bufAppendC('(');

    bufAppendS("HeteroElements1");

    bufAppendC(' ');

    shHeteroElement(p->u.heteroelements1_.heteroelement_);
  bufAppendC(' ');
    shHeteroElements(p->u.heteroelements1_.heteroelements_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing HeteroElements!\n");
    exit(1);
  }
}

void shHeteroElement(HeteroElement p)
{
  switch(p->kind)
  {
  case is_HeteroElementString:
    bufAppendC('(');

    bufAppendS("HeteroElementString");

    bufAppendC(' ');

    shString(p->u.heteroelementstring_.string_);

    bufAppendC(')');

    break;
  case is_HeteroElementDouble:
    bufAppendC('(');

    bufAppendS("HeteroElementDouble");

    bufAppendC(' ');

    shDouble(p->u.heteroelementdouble_.double_);

    bufAppendC(')');

    break;
  case is_HeteroElementInteger:
    bufAppendC('(');

    bufAppendS("HeteroElementInteger");

    bufAppendC(' ');

    shInteger(p->u.heteroelementinteger_.integer_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing HeteroElement!\n");
    exit(1);
  }
}

void shFUNC(FUNC p)
{
  switch(p->kind)
  {
  case is_FUNC1:
    bufAppendC('(');

    bufAppendS("FUNC1");

    bufAppendC(' ');

    shIdent(p->u.func1_.ident_);
  bufAppendC(' ');
    shBlock(p->u.func1_.block_);

    bufAppendC(')');

    break;
  case is_FUNC2:
    bufAppendC('(');

    bufAppendS("FUNC2");

    bufAppendC(' ');

    shIdent(p->u.func2_.ident_);

    bufAppendC(')');

    break;
  case is_FUNC3:
    bufAppendC('(');

    bufAppendS("FUNC3");

    bufAppendC(' ');

    shIdent(p->u.func3_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.func3_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing FUNC!\n");
    exit(1);
  }
}

void shVAILA(VAILA p)
{
  switch(p->kind)
  {
  case is_VAILA1:
    bufAppendC('(');

    bufAppendS("VAILA1");

    bufAppendC(' ');

    shInteger(p->u.vaila1_.integer_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing VAILA!\n");
    exit(1);
  }
}

void shLABEL(LABEL p)
{
  switch(p->kind)
  {
  case is_LABEL1:
    bufAppendC('(');

    bufAppendS("LABEL1");

    bufAppendC(' ');

    shInteger(p->u.label1_.integer_);
  bufAppendC(' ');
    shBlock(p->u.label1_.block_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing LABEL!\n");
    exit(1);
  }
}

void shConjValues(ConjValues p)
{
  switch(p->kind)
  {
  case is_ConjValuesVALUE:
    bufAppendC('(');

    bufAppendS("ConjValuesVALUE");

    bufAppendC(' ');

    shVALUE(p->u.conjvaluesvalue_.value_);

    bufAppendC(')');

    break;
  case is_ConjValues1:
    bufAppendC('(');

    bufAppendS("ConjValues1");

    bufAppendC(' ');

    shVALUE(p->u.conjvalues1_.value_);
  bufAppendC(' ');
    shConjValues(p->u.conjvalues1_.conjvalues_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ConjValues!\n");
    exit(1);
  }
}

void shConjValues2D(ConjValues2D p)
{
  switch(p->kind)
  {
  case is_ConjValues2D1:
    bufAppendC('(');

    bufAppendS("ConjValues2D1");

    bufAppendC(' ');

    shConjValues(p->u.conjvalues2d1_.conjvalues_);

    bufAppendC(')');

    break;
  case is_ConjValues2D2:
    bufAppendC('(');

    bufAppendS("ConjValues2D2");

    bufAppendC(' ');

    shConjValues(p->u.conjvalues2d2_.conjvalues_);
  bufAppendC(' ');
    shConjValues2D(p->u.conjvalues2d2_.conjvalues2d_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing ConjValues2D!\n");
    exit(1);
  }
}

void shPERMA(PERMA p)
{
  switch(p->kind)
  {
  case is_LConst:
    bufAppendC('(');

    bufAppendS("LConst");

    bufAppendC(' ');

    shType(p->u.lconst_.type_);
  bufAppendC(' ');
    shIdent(p->u.lconst_.ident_);
  bufAppendC(' ');
    shVALUE(p->u.lconst_.value_);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing PERMA!\n");
    exit(1);
  }
}

void shAPONTA(APONTA p)
{
  switch(p->kind)
  {
  case is_LPoint:
    bufAppendC('(');

    bufAppendS("LPoint");

    bufAppendC(' ');

    shType(p->u.lpoint_.type_);
  bufAppendC(' ');
    shIdent(p->u.lpoint_.ident_1);
  bufAppendC(' ');
    shIdent(p->u.lpoint_.ident_2);

    bufAppendC(')');

    break;

  default:
    fprintf(stderr, "Error: bad kind field when showing APONTA!\n");
    exit(1);
  }
}

void shInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppendS(tmp);
}
void shDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppendS(tmp);
}
void shChar(Char c)
{
  bufAppendC('\'');
  bufEscapeC(c);
  bufAppendC('\'');
}
void shString(String s)
{
  bufAppendC('\"');
  bufEscapeS(s);
  bufAppendC('\"');
}
void shIdent(String s)
{
  bufAppendC('\"');
  bufAppendS(s);
  bufAppendC('\"');
}

void bufEscapeS(const char *s)
{
  if (s) while (*s) bufEscapeC(*s++);
}
void bufEscapeC(const char c)
{
  switch(c)
  {
    case '\f': bufAppendS("\\f" ); break;
    case '\n': bufAppendS("\\n" ); break;
    case '\r': bufAppendS("\\r" ); break;
    case '\t': bufAppendS("\\t" ); break;
    case '\v': bufAppendS("\\v" ); break;
    case '\\': bufAppendS("\\\\"); break;
    case '\'': bufAppendS("\\'" ); break;
    case '\"': bufAppendS("\\\""); break;
    default: bufAppendC(c);
  }
}

void bufAppendS(const char *s)
{
  size_t len = strlen(s);
  size_t n;
  while (cur_ + len >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  for(n = 0; n < len; n++)
  {
    buf_[cur_ + n] = s[n];
  }
  cur_ += len;
  buf_[cur_] = 0;
}
void bufAppendC(const char c)
{
  if (cur_ + 1 >= buf_size)
  {
    buf_size *= 2; /* Double the buffer size */
    resizeBuffer();
  }
  buf_[cur_] = c;
  cur_++;
  buf_[cur_] = 0;
}
void bufReset(void)
{
  cur_ = 0;
  buf_size = BUFFER_INITIAL;
  resizeBuffer();
  memset(buf_, 0, buf_size);
}
void resizeBuffer(void)
{
  char *temp = (char *) malloc(buf_size);
  if (!temp)
  {
    fprintf(stderr, "Error: Out of memory while attempting to grow buffer!\n");
    exit(1);
  }
  if (buf_)
  {
    strncpy(temp, buf_, buf_size); /* peteg: strlcpy is safer, but not POSIX/ISO C. */
    free(buf_);
  }
  buf_ = temp;
}
char *buf_;
size_t cur_, buf_size;

