/* File generated by the BNF Converter (bnfc 2.9.5). */

#ifndef SKELETON_HEADER
#define SKELETON_HEADER
/* You might want to change the above name. */

#include "Absyn.h"


void visitS(S p);
void visitBlock(Block p);
void visitCMDS(CMDS p);
void visitCMD(CMD p);
void visitATRIB(ATRIB p);
void visitEXP(EXP p);
void visitUAI(UAI p);
void visitOPerL(OPerL p);
void visitOPerA(OPerA p);
void visitOPL(OPL p);
void visitZOIA(ZOIA p);
void visitVEMCA(VEMCA p);
void visitQUANTO(QUANTO p);
void visitPA(PA p);
void visitVALUE(VALUE p);
void visitType(Type p);
void visitTREM(TREM p);
void visitSTRUCT(STRUCT p);
void visitHeteroElements(HeteroElements p);
void visitHeteroElement(HeteroElement p);
void visitFUNC(FUNC p);
void visitVAILA(VAILA p);
void visitLABEL(LABEL p);
void visitConjValues(ConjValues p);
void visitConjValues2D(ConjValues2D p);
void visitPERMA(PERMA p);
void visitAPONTA(APONTA p);


void visitIdent(Ident i);
void visitInteger(Integer i);
void visitDouble(Double d);
void visitChar(Char c);
void visitString(String s);

#endif

